# Generated by Django 4.1.7 on 2023-06-02 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[('Admin', 'Admin'), ('Voter', 'Voter')], default=2, max_length=100),
        ),
    ]
